name: PR Review Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with GitHub
        run: |
          echo "Using GH_TOKEN for authentication"
          gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"

