name: PR Review Workflow

on:
  pull_request:
    branches:
      - main
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a simple script
        run: echo "This is a placeholder for a PR review task."
