name: PR Review Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with GitHub
        run: |
          echo "Using GH_TOKEN for authentication"
          gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "Workflow succeeded! 🎉"
          SLACK_COLOR: "#36a64f"

      - name: Send Email Notification via Mailgun
        run: |
          curl --request POST \
            --url https://api.mailgun.net/v3/sandboxeff25f83f3b7454092d48cf3ac3245e8.mailgun.org/messages \
            --user "api:${{ secrets.MAILGUN_API_KEY }}" \
            --form "from=Your Workflow <yuvaraj17.4win@gmail.com>" \
            --form "to=yuvaraj4win.17@gmail.com" \
            --form "subject=Workflow Status Update" \
            --form "text=Your GitHub Actions workflow has succeeded! 🎉"
