name: Weekly PR Review Summary

on:
  schedule:
    - cron: '0 9 * * 1'  # Runs at 9:00 AM every Monday
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install requests

      - name: Generate PR review summary
        id: generate-summary
        run: |
          # Fetch PR reviews from GitHub API
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&sort=updated&direction=desc")

          # Extract relevant data (e.g., PR titles, reviewers, comments)
          summary=$(echo "$response" | jq -r '.[] | "\(.title) - Reviewed by: \(.requested_reviewers[].login)"')

          # Save summary to a file
          echo "$summary" > pr_summary.txt

          # Output summary for debugging
          echo "Weekly PR Review Summary:"
          cat pr_summary.txt

      - name: Send summary to Slack
        if: success()
        uses: slackapi/slack-github-action@v1
        with:
          slack-message: |
            *Weekly PR Review Summary*
            $(cat pr_summary.txt)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
